#
# rakefile to run all sipp tests and generate xml output of testresults
#
#	@author richard lum
# @date 20120329
#
# usage:  rake
# 			output will be in sub directory defined by CI_REPORTS

require 'rubygems'
require 'ci/reporter/rake/test_unit'

require 'rake'
require 'rake/testtask'

task :default => [:test_units]
task :test_units =>  ['ci:setup:testunit']

#ENV['CI_CAPTURE']="off"
ENV['CI_REPORTS']="testresults"

desc "Run tests"
Rake::TestTask.new("test_units") { |t|
	#t.pattern = 'verify*.rb'
	t.test_files = FileList['verify*.rb','aa_expires*.rb', 'dump_sequence_diagram.rb', 
										'include*.rb', 'init_keywords.rb', 'short_headers.rb', 'exec.rb',
										'zero_content*.rb']
	t.verbose = true
	t.warning = false
}
