#
# rakefile to run all sipp tests and generate xml output of testresults
#
#	@author richard lum
# @date 20120329
#
# usage:  rake
# 			output will be in sub directory defined by CI_REPORTS

require 'rubygems'
require 'ci/reporter/rake/test_unit'
require 'rake'
require 'rake/testtask'

# dependancies
task :default => [:testrb]
task :test_units =>  ['ci:setup:testunit']
task :testrb => [:test_rb]
task :test_rb =>  ['ci:setup:testunit']

#ci_reports environment variables
ENV['CI_CAPTURE']="on"
ENV['CI_REPORTS']="testresults"

# no need to maintain explicit list of tests here. carry on with test.rb
desc "Run tests directly"
Rake::TestTask.new("test_units") { |t|
	#t.pattern = 'verify*.rb'
	t.test_files = FileList['verify*.rb','aa_expires*.rb', 'dump_sequence_diagram.rb', 
										'include*.rb', 'init_keywords.rb', 'short_headers.rb', 'exec.rb',
										'zero_content*.rb']
	t.verbose = true
	t.warning = false
}


# usage: rake testrb
#   todo verify xml output works as desired since test.rb calls tests rather than directly from TestTask
desc "call test.rb instead of tests directly"
Rake::TestTask.new("test_rb") { |t|
  t.test_files = FileList['test.rb']
  t.verbose = true
  t.warning = false
}
  
